#
# .github/workflows/release.yml
#
---
name: release
defaults:
  run:
    # Prefixes all `run` commands with the following command to force them to run outside Rosetta.
    shell: arch -arm64 bash --noprofile --norc -eo pipefail {0}
on:
  release:
    types: [published]
jobs:
  start:
    runs-on: macos-14
    outputs:
      dry_run: ${{ steps.dry_run.outputs.test }}
      mas_version: ${{ steps.mas_version.outputs.test }}
      release_branch: ${{ steps.release_branch.outputs.test }}
      release_commit: ${{ steps.release_commit.outputs.test }}
    steps:
      # Logs event details and sets `DRY_RUN` env var
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      # https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=published#release
      - name: 🔈 Log release event
        # This step will only run for a real 'release' event.
        if: ${{ github.event.release.name != '' }}
        run: |
          echo "Triggered by a release publication event (wet run)"
          echo "release.name: ${{ github.event.release.name }}"
          echo "release.tag_name: ${{ github.event.release.tag_name }}"
          echo "release.target_commitish: ${{ github.event.release.target_commitish }}"
          echo -e "release.body: \n${{ github.event.release.body }}"

      - id: dry_run
        run: |
          echo "DRY_RUN=false" >>"$GITHUB_OUTPUT"

      - id: mas_version
        run: |
          echo "MAS_VERSION=${{ github.event.release.tag_name }}" >>"$GITHUB_OUTPUT"

      - id: release_branch
        run: |
          echo "RELEASE_BRANCH=releases/release-${{ github.event.release.tag_name }}" >>"$GITHUB_OUTPUT"

      - id: release_commit
        run: |
          echo "RELEASE_COMMIT=${{ github.event.release.target_commitish }}" >>"$GITHUB_OUTPUT"

  prepare-release:
    runs-on: macos-14
    needs: [start]
    steps:
      - uses: actions/checkout@v4
        with:
          # A fetch-depth of 0 includes all history and tags for script/version
          fetch-depth: 0

      - name: 🔀 Create release branch
        env:
          RELEASE_BRANCH: ${{ needs.start.outputs.release_branch }}
        run: |
          git branch "${RELEASE_BRANCH }"
          git switch "${RELEASE_BRANCH }"

      - name: 🔖 Update version
        env:
          MAS_VERSION: ${{ needs.start.outputs.mas_version }}
          RELEASE_COMMIT: ${{ needs.start.outputs.release_commit }}
        run: |
          script/version_bump "${MAS_VERSION}" "${RELEASE_COMMIT}"

      - name: 💾 Commit changes
        env:
          MAS_VERSION: ${{ needs.start.outputs.mas_version }}
        run: |
          git add \
            "Homebrew/mas.rb" \
            "Homebrew/mas-tap.rb" \
            "Sources/MasKit/Package.swift"
          git commit \
            --message="🔖 Version ${MAS_VERSION}"

      - name: ⤴️ Open PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAS_VERSION: ${{ needs.start.outputs.mas_version }}
          RELEASE_BRANCH: ${{ needs.start.outputs.release_branch }}
        run: |
          gh pr create \
            --base main \
            --head "${RELEASE_BRANCH}" \
            --title "🔖 Version ${MAS_VERSION}" \
            --body "This PR contains the changes from releasing version [${MAS_VERSION}](https://github.com/mas-cli/mas/releases/tag/${MAS_VERSION})."

  pkg-installer:
    runs-on: macos-14
    needs: [start, prepare-release]
    steps:
      - uses: actions/checkout@v4
        with:
          # A fetch-depth of 0 includes all history and tags for script/version
          fetch-depth: 0

      - name: 👢 Bootstrap
        run: |
          script/bootstrap -f

      # Important to trigger a universal build first as package just works with
      # the `mas` binary in finds in the build dir.
      - name: 🏗️ Build Universal
        run: |
          script/build --universal

      - name: 📦 macOS Package
        run: |
          script/package

      - name: 🚀 Upload mas.pkg
        env:
          DRY_RUN: ${{ needs.start.outputs.dry_run }}
          MAS_VERSION: ${{ needs.start.outputs.mas_version }}
        if: ${{ needs.start.outputs.dry_run == 'false' }}
        run: |
          gh release upload ${MAS_VERSION} \
            .build/mas.pkg

  homebrew-tap:
    runs-on: macos-14
    needs: [start, prepare-release]
    steps:
      - uses: actions/checkout@v4
        with:
          # A fetch-depth of 0 includes all history and tags for script/version
          fetch-depth: 0

      - name: 👢 Bootstrap
        run: |
          script/bootstrap -f

      - name: 🚰 Update mas tap formula
        env:
          DRY_RUN: ${{ needs.start.outputs.dry_run }}
          MAS_VERSION: ${{ needs.start.outputs.mas_version }}
        run: |
          DRY_RUN=${DRY_RUN} \
            script/brew_tap_update ${MAS_VERSION}

      - name: 🚀 Upload Bottles
        env:
          DRY_RUN: ${{ needs.start.outputs.dry_run }}
          MAS_VERSION: ${{ needs.start.outputs.mas_version }}
        if: ${{ needs.start.outputs.dry_run == 'false' }}
        run: |
          gh release upload ${MAS_VERSION} \
            .build/bottles/mas-*.bottle.tar.gz

  homebrew-core:
    runs-on: macos-14
    needs: [start, prepare-release, homebrew-tap]
    steps:
      - uses: actions/checkout@v4
        with:
          # A fetch-depth of 0 includes all history and tags for script/version
          fetch-depth: 0

      - name: 👢 Bootstrap
        run: |
          script/bootstrap -f

      - name: 🍺 Update Homebrew mas formula
        env:
          DRY_RUN: ${{ needs.start.outputs.dry_run }}
          MAS_VERSION: ${{ needs.start.outputs.mas_version }}
        run: |
          DRY_RUN=${DRY_RUN} \
            script/brew_core_update ${MAS_VERSION}

